### PR TITLE
updated documentation to better reflect what epsfunc should do 

### PR DESCRIPTION
**Pull request by DavidRimel**
updated the documentation for what the epsfunc should do. As the old documentation i found the be incorrect.

### CODE REVIEW

**Comment by lbolla** [comment]
@DavidRimel Thanks for the PR. Can you please fix the issue highlighted above by Codacity and I'll be happy to merge your changes. Thanks!

**Comment by DavidRimel** [comment]
ok i fixed the issue and now my commits pass all the checks!

**Comment by DanHickstein** [comment]
Thanks for fixing my haphazard docstrings @DavidRimel! This makes it much easier to understand.

I noticed in your profile that you are from Boulder. I am also in Boulder, working at NIST and using EMPy to simulation the refractive index (and dispersion) of on-chip waveguides for supercontinuum generation.

**Comment by lbolla** [comment]
Thanks both!

**Comment by DavidRimel** [comment]
@DanHickstein  thats awsome! im working at TechX using EMpy to solve for guided modes for our simulations of photonic devices such as micro ring resonators, arrayed wave guides, etc....

**Comment by DanHickstein** [comment]
Cool! We are also doing work with microring resonators. I didn't realize TechX was into that sort of thing - I thought that they were mainly plasma codes. I'd love to grab a coffee sometime and learn more about your research. Drop me an e-mail: danhickstein@gmail.com.

**Pull request merged**
